name = "kinetic-api"
main = "src/index.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "kinetic-db"
database_id = "local-kinetic-d1-id"
migrations_dir = "migrations"

[vars]
ENVIRONMENT = "development"
